INSERT INTO coins (coingecko_id, symbol, name, rank) VALUES
('bitcoin', 'BTC', 'Bitcoin', 1),
('ethereum', 'ETH', 'Ethereum', 2),
('tether', 'USDT', 'Tether', 3),
('binancecoin', 'BNB', 'BNB', 4),
('solana', 'SOL', 'Solana', 5),
('ripple', 'XRP', 'XRP', 6),
('usd-coin', 'USDC', 'USDC', 7),
('staked-ether', 'STETH', 'Lido Staked Ether', 8),
('dogecoin', 'DOGE', 'Dogecoin', 9),
('tron', 'TRX', 'TRON', 10),
('cardano', 'ADA', 'Cardano', 11),
('avalanche-2', 'AVAX', 'Avalanche', 12),
('chainlink', 'LINK', 'Chainlink', 13),
('shiba-inu', 'SHIB', 'Shiba Inu', 14),
('polkadot', 'DOT', 'Polkadot', 15),
('bitcoin-cash', 'BCH', 'Bitcoin Cash', 16),
('near', 'NEAR', 'NEAR Protocol', 17),
('uniswap', 'UNI', 'Uniswap', 18),
('litecoin', 'LTC', 'Litecoin', 19),
('matic-network', 'MATIC', 'Polygon', 20),
('internet-computer', 'ICP', 'Internet Computer', 21),
('stellar', 'XLM', 'Stellar', 22),
('filecoin', 'FIL', 'Filecoin', 23),
('ethereum-classic', 'ETC', 'Ethereum Classic', 24),
('monero', 'XMR', 'Monero', 25),
('aave', 'AAVE', 'Aave', 26),
('vechain', 'VET', 'VeChain', 27),
('cosmos', 'ATOM', 'Cosmos Hub', 28),
('algorand', 'ALGO', 'Algorand', 29),
('the-graph', 'GRT', 'The Graph', 30),
('fantom', 'FTM', 'Fantom', 31),
('theta-token', 'THETA', 'Theta Network', 32),
('quant-network', 'QNT', 'Quant', 33),
('elrond-erd-2', 'EGLD', 'MultiversX', 34),
('tezos', 'XTZ', 'Tezos', 35),
('flow', 'FLOW', 'Flow', 36),
('hedera-hashgraph', 'HBAR', 'Hedera', 37),
('axie-infinity', 'AXS', 'Axie Infinity', 38),
('the-sandbox', 'SAND', 'The Sandbox', 39),
('decentraland', 'MANA', 'Decentraland', 40),
('chiliz', 'CHZ', 'Chiliz', 41),
('enjincoin', 'ENJ', 'Enjin Coin', 42),
('basic-attention-token', 'BAT', 'Basic Attention Token', 43),
('1inch', '1INCH', '1inch Network', 44),
('compound', 'COMP', 'Compound', 45),
('maker', 'MKR', 'Maker', 46),
('dash', 'DASH', 'Dash', 47),
('zcash', 'ZEC', 'Zcash', 48),
('neo', 'NEO', 'NEO', 49),
('waves', 'WAVES', 'Waves', 50)
ON CONFLICT (coingecko_id) DO NOTHING;
